# Site settings
title: Gerard Simpson
email: gardeimspons@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gerard Simpson, Web Developer, lover of web technologies, modern JS frameworks, and creating things.
baseurl: "/GerardSimpson" # the subpath of your site, e.g. /blog/
url: "https://node-gs.github.io" # the base hostname & protocol for your site
twitter_username: GerardSimpson1
github_username:  node-gs
exclude: [node_modules]
# Build settings
markdown: kramdown
collections:
  projects:
    output: true
